{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8e1562b3-8c64-4462-80ea-43888a03af53",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting auto display for cadquery Workplane and Shape\n",
      "\n",
      "Enabling jupyter_cadquery replay\n",
      "Note: To get rid of this warning, use 'enable_replay(False)'\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "   Copyright 2023 Raphaël Isvelin\n",
    "\n",
    "   Licensed under the Apache License, Version 2.0 (the \"License\");\n",
    "   you may not use this file except in compliance with the License.\n",
    "   You may obtain a copy of the License at\n",
    "\n",
    "       http://www.apache.org/licenses/LICENSE-2.0\n",
    "\n",
    "   Unless required by applicable law or agreed to in writing, software\n",
    "   distributed under the License is distributed on an \"AS IS\" BASIS,\n",
    "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
    "   See the License for the specific language governing permissions and\n",
    "   limitations under the License.\n",
    "\"\"\"\n",
    "\n",
    "VIEWER_THEME = \"light\"  # light, dark\n",
    "VIEWER_HEIGHT = 900\n",
    "ENABLE_REPLAY = True\n",
    "\n",
    "import cadquery as cq\n",
    "\n",
    "from jupyter_cadquery import show as jcq_show\n",
    "from jupyter_cadquery import (\n",
    "    versions,\n",
    "    PartGroup, Part, \n",
    "    get_viewer, close_viewer, get_viewers, close_viewers, open_viewer, set_defaults, get_defaults, open_viewer, get_pick,\n",
    ")\n",
    "\n",
    "from jupyter_cadquery.replay import replay, enable_replay, disable_replay\n",
    "enable_replay(ENABLE_REPLAY)\n",
    "\n",
    "from cq_warehouse.fastener import (\n",
    "    polygon_diagonal,\n",
    "    read_fastener_parameters_from_csv,\n",
    "    Screw, SocketHeadCapScrew, HeatSetNut, PlainWasher,\n",
    "    HexNutWithFlange, HexHeadScrew, PanHeadScrew, CounterSunkScrew\n",
    ")\n",
    "import cq_warehouse.extensions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ca8c0003-008c-41ae-b296-10d85e0fda89",
   "metadata": {},
   "outputs": [],
   "source": [
    "cv = open_viewer(\"Assembly\", anchor=\"right\")  # sets default viewer\n",
    "\n",
    "objects_to_hide = [\n",
    "    \"/Masks\"\n",
    "]\n",
    "\n",
    "def hide_objects_matching_strings(strings, keep_edges=True, cv=cv):\n",
    "    for state in cv.widget.states:\n",
    "        should_hide = False\n",
    "        for s in strings:\n",
    "            if s in state:\n",
    "                should_hide = True\n",
    "                break\n",
    "        if should_hide:\n",
    "            cv.update_states({\n",
    "                state: (0, 0 if keep_edges else 0),\n",
    "            })\n",
    "            \n",
    "def show(obj, viewer=\"Assembly\", anchor=\"right\", hide_contains=objects_to_hide):\n",
    "    cv = jcq_show(\n",
    "        obj,\n",
    "        viewer=viewer,\n",
    "        anchor=anchor,\n",
    "        #cad_width=1640,\n",
    "        height=VIEWER_HEIGHT,\n",
    "        theme=VIEWER_THEME,\n",
    "        collapse=1,\n",
    "        optimal_bb=True,\n",
    "        render_edges=True,\n",
    "        axes=True,\n",
    "        axes0=True,\n",
    "        grid=[True, True, True],\n",
    "        #black_edges=True,\n",
    "        reset_camera=False,\n",
    "        #show_parent=True,\n",
    "        #timeit=True,\n",
    "        #js_debug=True\n",
    "    )\n",
    "    hide_objects_matching_strings(hide_contains, cv=cv)\n",
    "\n",
    "def show_b(obj, viewer=\"Quick\", hide_contains=objects_to_hide):\n",
    "    cv2 = open_viewer(viewer, anchor=\"split-bottom\")\n",
    "    show(obj, viewer, anchor=\"split-bottom\", hide_contains=hide_contains)\n",
    "\n",
    "def show_x(obj, hide_contains=objects_to_hide):\n",
    "    show(obj, viewer=None, hide_contains=hide_contains)\n",
    "\n",
    "def show_part(part: Part, bottom=False):\n",
    "    footprint_assembly = (\n",
    "        cq.Assembly()\n",
    "            .add(part.debug_objects.footprint.inside, name=\"Inside\", color=cq.Color(1, 0, 1))\n",
    "            .add(part.debug_objects.footprint.outside, name=\"Outside\", color=cq.Color(0, 1, 1))\n",
    "    )\n",
    "    test_assembly = (\n",
    "        cq.Assembly(None, name=\"test_assembly\")\n",
    "            .add(part.mask, name=\"Mask\", color=cq.Color(0, 1, 0))\n",
    "            .add(part.part, name=\"Part\")\n",
    "            .add(part.assembly_parts_to_cq_assembly(), name=\"Part assembly\")\n",
    "            .add(footprint_assembly, name=\"Footprint\")\n",
    "    )\n",
    "    debug_assembly = cq.Assembly()\n",
    "    debug_assembly.add(part.debug_objects.hole, name=\"Hole\", color=cq.Color(1, 0, 0))\n",
    "    for debug_obj_name in part.debug_objects.others.keys():\n",
    "        obj = part.debug_objects.others[debug_obj_name]\n",
    "        if not isinstance(obj, dict):\n",
    "            debug_assembly.add(obj, name=debug_obj_name, color=cq.Color(0.5, 0.7, 0.5))\n",
    "    test_assembly.add(debug_assembly, name=\"Debug\")\n",
    "\n",
    "    if bottom: show_b(test_assembly)\n",
    "    else: show(test_assembly)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fff6cd06-66b6-423c-a9d1-77dc7e7f8bb1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "bec67c4d-7749-4915-99ed-7cf5deaffbae",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Union\n",
    "from cq_enclosure_builder.part import Part\n",
    "from cq_enclosure_builder.parts.common.screws_providers import TinyBlockFlatHeadScrewProvider\n",
    "\n",
    "\n",
    "class RectAirVentPart(Part):\n",
    "    \"\"\"\n",
    "    Class to make basic rectangular vents, with optional screws for fan.\n",
    "\n",
    "    Needs refactoring.\n",
    "    Hasn't been tested much besides the default parameters.\n",
    "    \"\"\"\n",
    "    def __init__(\n",
    "        self,\n",
    "        enclosure_wall_thickness,\n",
    "        width = 30,\n",
    "        length = 25,\n",
    "        thickness = 6,\n",
    "        margin = 0.5,\n",
    "        hole_angle = 25,\n",
    "        hole_width = 1.6,\n",
    "        distance_between_holes = 4,\n",
    "        taper = True,\n",
    "        taper_margin = 3,\n",
    "        taper_angle = 35,\n",
    "        with_fan_screws: Union[FanSize, None] = FanSize._30_MM,\n",
    "        fan_screws_size: str = \"m3\",\n",
    "        fan_screws_taper_mode: TaperOptions = TaperOptions.XY_TAPER,\n",
    "        fan_screws_taper_rotation: float = 0,\n",
    "        fan_screws_taper_incline: float = 0.75,\n",
    "        fan_screws_taper_on: str = \"1100\"  # TODO cleanup one day; sorry future self, just want to be done with it :shrug:\n",
    "    ):\n",
    "        super().__init__()\n",
    "\n",
    "        # Board\n",
    "        board = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(width, length, thickness, centered=(True, True, False))\n",
    "        )\n",
    "\n",
    "        # Add holes\n",
    "        single_hole = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(hole_width, length, thickness*6, centered=(True, True, False))\n",
    "                .translate([0, 0, -(thickness*3)])\n",
    "                .rotate((0, 0, 0), (0, 1, 0), hole_angle)\n",
    "        )\n",
    "\n",
    "        all_holes = cq.Assembly()\n",
    "        hole_x = 0\n",
    "        while hole_x < width/2:\n",
    "            all_holes.add(single_hole.translate([hole_x, 0, 0]))\n",
    "            all_holes.add(single_hole.translate([-hole_x, 0, 0]))\n",
    "            hole_x = hole_x + distance_between_holes\n",
    "\n",
    "        board = board.cut(all_holes.toCompound())\n",
    "\n",
    "        # Add frame\n",
    "        board = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(width + margin*2, length + margin*2, thickness - enclosure_wall_thickness, centered=(True, True, False))\n",
    "                .translate([0, 0, enclosure_wall_thickness])\n",
    "                .cut(cq.Workplane(\"front\").box(width, length, thickness, centered=(True, True, False)))\n",
    "                .add(board)\n",
    "        )        \n",
    "\n",
    "        # Pyramid\n",
    "        if taper:\n",
    "            pyramid = (\n",
    "                cq.Workplane(\"front\")\n",
    "                    .rect(width + margin*2 + taper_margin*2, length + margin*2 + taper_margin*2)\n",
    "                    .extrude(30, taper=taper_angle)\n",
    "                    .cut(cq.Workplane(\"front\").rect(width + 4, length + 4).extrude(40).translate([0, 0, thickness - enclosure_wall_thickness]))\n",
    "                    .cut(cq.Workplane(\"front\").rect(width, length).extrude(thickness - enclosure_wall_thickness).translate([0, 0, 0]))\n",
    "                    .translate([0, 0, enclosure_wall_thickness])\n",
    "            )\n",
    "            board = board.add(pyramid)\n",
    "\n",
    "        # Mask & footprint\n",
    "        mask = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(width, length, enclosure_wall_thickness, centered=(True, True, False))\n",
    "        )\n",
    "\n",
    "        inside_footprint_thickness = 4\n",
    "        footprint_in = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(width, length)\n",
    "                .extrude(inside_footprint_thickness)\n",
    "                .translate([0, 0, enclosure_wall_thickness])\n",
    "        )\n",
    "\n",
    "        # Fan screws\n",
    "        if with_fan_screws is not None:\n",
    "            fan_screws_a = RectAirVentPart._get_fan_screws_blocks(\n",
    "                enclosure_wall_thickness,\n",
    "                with_fan_screws,\n",
    "                block_thickness=thickness,  # - enclosure_wall_thickness,\n",
    "                screw_size=fan_screws_size,\n",
    "                screw_block_taper_option=fan_screws_taper_mode,\n",
    "                screw_block_taper_rotation=fan_screws_taper_rotation,\n",
    "                screw_block_taper_incline=fan_screws_taper_incline,\n",
    "                screw_block_taper_on=fan_screws_taper_on\n",
    "            )\n",
    "            fan_screws = fan_screws_a[\"screws\"]  #.translate([0, 0, enclosure_wall_thickness])\n",
    "            fan_masks = fan_screws_a[\"masks\"]  #.translate([0, 0, enclosure_wall_thickness])\n",
    "            footprint_in = footprint_in.add(fan_screws_a[\"footprint_in\"])\n",
    "\n",
    "            board = board.cut(fan_masks).add(fan_screws)\n",
    "            mask = mask.add(fan_masks)\n",
    "\n",
    "        self.part = board\n",
    "        self.mask = mask\n",
    "\n",
    "        self.size.width     = width + margin*2 + taper_margin*2\n",
    "        self.size.length    = length + margin*2 + taper_margin*2\n",
    "        self.size.thickness = thickness\n",
    "\n",
    "        self.inside_footprint = (self.size.width, self.size.length)  # TODO should account for the screw blocks (incl. taper)\n",
    "        self.inside_footprint_offset = (0, 0)\n",
    "        self.outside_footprint = (self.size.width, self.size.length)\n",
    "        footprint_in = footprint_in.add(board)\n",
    "        outside_footprint_thickness = 2\n",
    "        footprint_out = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(*self.outside_footprint)\n",
    "                .extrude(outside_footprint_thickness)\n",
    "                .translate([-0, 0, -outside_footprint_thickness])\n",
    "        )\n",
    "        self.debug_objects.footprint.inside  = footprint_in\n",
    "        self.debug_objects.footprint.outside = footprint_out\n",
    "        \n",
    "        self.debug_objects.hole = None\n",
    "\n",
    "    @staticmethod\n",
    "    def _get_fan_screws_blocks(\n",
    "        enclosure_wall_thickness,\n",
    "        fan_size: FanSize,\n",
    "        block_thickness: float,\n",
    "        screw_size: str = \"m2\",\n",
    "        screw_block_taper_option: TaperOptions = TaperOptions.XY_TAPER,\n",
    "        screw_block_taper_rotation: float = 0,\n",
    "        screw_block_taper_incline: float = 0.75,\n",
    "        screw_block_taper_on: str = \"1111\",  # should taper that specific screw block? same order as screws_pos\n",
    "        screw_block_hole_distance_to_wall: float = 0.8\n",
    "    ):\n",
    "        screw = ScrewBlock(screw_provider=TinyBlockFlatHeadScrewProvider).build(\n",
    "            screw_size, block_thickness, enclosure_wall_thickness, screw_hole_depth=block_thickness-screw_block_hole_distance_to_wall, fill_pointy_bit=True,\n",
    "            taper=screw_block_taper_option, taper_rotation=screw_block_taper_rotation, xy_taper_incline=screw_block_taper_incline, xy_taper_from=enclosure_wall_thickness)\n",
    "        screw_no_taper = ScrewBlock(screw_provider=TinyBlockFlatHeadScrewProvider).build(\n",
    "            screw_size, block_thickness, enclosure_wall_thickness, screw_hole_depth=block_thickness-screw_block_hole_distance_to_wall, fill_pointy_bit=True)\n",
    "\n",
    "        distance_between_screws = None  # center to center\n",
    "        footprint_size = None\n",
    "        footprint_thickness = None\n",
    "        # TODO Refactor when needed\n",
    "        if fan_size == FanSize._25_MM:\n",
    "            distance_between_screws = 16.9 + 2.9\n",
    "            footprint_size = 25\n",
    "            footprint_thickness = 7\n",
    "        elif fan_size == FanSize._30_MM:\n",
    "            distance_between_screws = 20.8 + 3.2\n",
    "            footprint_size = 30\n",
    "            footprint_thickness = 8\n",
    "        elif fan_size == FanSize._40_MM:\n",
    "            distance_between_screws = 28.9 + 3.2\n",
    "            footprint_size = 40\n",
    "            footprint_thickness = 10.8\n",
    "        else:\n",
    "            raise ValueError(\"Unknown FanSize\")\n",
    "\n",
    "        hdbs = distance_between_screws/2\n",
    "\n",
    "        screws_pos = [\n",
    "            (-hdbs,  hdbs),  # TR\n",
    "            ( hdbs,  hdbs),  # TL\n",
    "            ( hdbs, -hdbs),  # BL\n",
    "            (-hdbs, -hdbs),  # BR\n",
    "        ]\n",
    "\n",
    "        screws = cq.Assembly()\n",
    "        masks = cq.Assembly()\n",
    "        for idx, sp in enumerate(screws_pos):\n",
    "            current_screw = screw if screw_block_taper_on[idx] == \"1\" else screw_no_taper  # see apologies in constructor :D\n",
    "            screws.add(current_screw[\"block\"].translate([*sp, 0]))\n",
    "            masks.add(current_screw[\"mask\"].translate([*sp, 0]))\n",
    "\n",
    "        footprint_in = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .rect(footprint_size, footprint_size)\n",
    "                .extrude(footprint_thickness)\n",
    "                .translate([0, 0, block_thickness])\n",
    "        )\n",
    "\n",
    "        return {\n",
    "            \"screws\": screws.toCompound(),\n",
    "            \"masks\": masks.toCompound(),\n",
    "            \"footprint_in\": footprint_in,\n",
    "            #\"base_plate\": base_plate.translate([0, 0, -enclosure_wall_thickness])\n",
    "        }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "f14d25ae-3973-4751-863e-40df6996ac9e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100% ⋮————————————————————————————————————————————————————————————⋮ (9/9)  0.46s\n"
     ]
    }
   ],
   "source": [
    "r = RectAirVentPart(2)\n",
    "\n",
    "show_part(r)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9af0d86a-d721-4e47-82ca-f2220801f1d4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb80ea53-3e62-40e0-b87f-f16ce2503561",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1642e4ee-87af-4880-a60d-4520063d8388",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "1203c2de-a14d-4b63-b8ad-f2627d3dfd40",
   "metadata": {},
   "source": [
    "## Build test parts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5e2149ef-cf0b-4fd8-bd99-f3e60144e4f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "VALIDATING CLASS: UsbCChengHaoRanEPart\n",
      "VALIDATING CLASS: UsbCChengHaoRanEPart\n",
      "VALIDATING CLASS: UsbA30VerticalCltgxddPart\n",
      "VALIDATING CLASS: UsbA30VerticalCltgxddPart\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "VALIDATING CLASS: EncoderEc11Part\n",
      "VALIDATING CLASS: Jack3_5mmXxxPart\n",
      "VALIDATING CLASS: Jack6_35mmPj612aPart\n",
      "TODO Need to move all workplanes so the hole's center is at 0,0\n",
      "VALIDATING CLASS: Hdmi5InchJrp5015Part\n",
      "VALIDATING CLASS: PotentiometerWh148Part\n",
      "VALIDATING CLASS: Banana4mmPart\n",
      "VALIDATING CLASS: BarrelPlugDc022bPart\n",
      "VALIDATING CLASS: RcaN1030Part\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (12/12)  0.17s\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.append(\"../src\")\n",
    "\n",
    "from cq_enclosure_builder import PartFactory as pf\n",
    "from cq_enclosure_builder import Panel, PanelSize\n",
    "from cq_enclosure_builder import Enclosure, Face\n",
    "from cq_enclosure_builder.knobs_and_caps import KNOB_12_6_x_15_8\n",
    "\n",
    "pf.set_default_types({\n",
    "    \"jack\": '6.35mm PJ-612A',\n",
    "    \"usb_a\": '3.0 vertical cltgxdd',\n",
    "    \"usb_c\": 'ChengHaoRan E',\n",
    "    \"button\": 'SPST PBS-24B-4',\n",
    "    \"encoder\": 'EC11',\n",
    "    \"screen\": 'HDMI 5 inch JRP5015',\n",
    "    \"potentiometer\": 'WH148',\n",
    "    \"banana\": '4mm',\n",
    "    \"barrel_plug\": 'DC-022B',\n",
    "    \"rca\": 'N1030',\n",
    "})\n",
    "pf.set_default_parameters({\n",
    "    \"enclosure_wall_thickness\": 2,\n",
    "    \"pot_knob\": KNOB_12_6_x_15_8\n",
    "})\n",
    "\n",
    "usb_c = pf.build_usb_c()\n",
    "usb_c_v = pf.build_usb_c(orientation_vertical=True)\n",
    "usb_a = pf.build_usb_a()\n",
    "usb_a_v = pf.build_usb_a(orientation_vertical=True)\n",
    "spst = pf.build_button()\n",
    "encoder = pf.build_encoder() \n",
    "jack_35 = pf.build_jack(part_type='3.5mm XXX')\n",
    "jack_635 = pf.build_jack()\n",
    "screen = pf.build_screen()\n",
    "pot = pf.build_potentiometer()\n",
    "banana = pf.build_banana()\n",
    "barrel_plug = pf.build_barrel_plug()\n",
    "rca = pf.build_rca()\n",
    "\n",
    "\n",
    "show_part(pot)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b01182c8-4cc9-4056-a9cc-04fad38043f2",
   "metadata": {},
   "source": [
    "## Panels etc."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "011258ac-a9d9-4c17-901a-0772125e9e1b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "70c8b066-3432-4ef0-a0d6-a3513bbd5a79",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "from cq_enclosure_builder import Face\n",
    "from cq_enclosure_builder.part import Part\n",
    "\n",
    "class PanelSize:\n",
    "    def __init__(self, width, length, wall_thickness, total_thickness):\n",
    "        self.width = width\n",
    "        self.length = length\n",
    "        self.wall_thickness = wall_thickness\n",
    "        self.total_thickness = total_thickness\n",
    "\n",
    "class Panel:\n",
    "    def __init__(self,\n",
    "                 face: Face,\n",
    "                 top_view_width,\n",
    "                 top_view_length,\n",
    "                 wall_thickness,\n",
    "                 color=None,\n",
    "                 part_color=None,\n",
    "                 alpha=1.0,\n",
    "                 lid_size_error_margin=0.0  # if provided, panel will be smaller than mask\n",
    "        ):\n",
    "        self.face = face\n",
    "        self.size = PanelSize(top_view_width, top_view_length, wall_thickness, wall_thickness)\n",
    "        self._color = color\n",
    "        if self._color == None:\n",
    "            self._color = self.face.default_color\n",
    "        self._part_color = part_color\n",
    "        if self._part_color == None:\n",
    "            self._part_color = self.face.default_part_color\n",
    "        self.panel = None\n",
    "        self.mask = self._rotate_to_face(\n",
    "            cq.Workplane(\"front\")\n",
    "                .workplane()\n",
    "                .box(top_view_width, top_view_length, wall_thickness, centered=(True, True, False))\n",
    "        )\n",
    "        self.debug_assemblies = {}\n",
    "        self.debug_assemblies[\"hole\"] = None\n",
    "        self.debug_assemblies[\"footprint_in\"] = None\n",
    "        self.debug_assemblies[\"footprint_out\"] = None\n",
    "        self.debug_assemblies[\"other\"] = None\n",
    "        self.debug_assemblies[\"combined\"] = cq.Assembly(None, name=self.face.label + \" - Debug\")\n",
    "        self.lid_size_error_margin = lid_size_error_margin\n",
    "        self._alpha = alpha\n",
    "        self._parts_to_add = []\n",
    "        self._screw_counter_sunks = []\n",
    "\n",
    "    def add(self, label: str, part: Part, rel_pos=None, abs_pos=None):\n",
    "        print(self.face.label + \": adding part '\" + label + \"'\")\n",
    "        pos = None\n",
    "        if rel_pos == None and abs_pos == None:\n",
    "            raise ValueError(\"Either rel_pos or abs_pos must be set.\")\n",
    "        elif rel_pos == None:\n",
    "            pos = (\n",
    "                abs_pos[0] - self.size.width/2,\n",
    "                abs_pos[1] - self.size.length/2\n",
    "            )\n",
    "        elif abs_pos==None:\n",
    "            pos = rel_pos\n",
    "        self._parts_to_add.append({\n",
    "            \"part\": part,\n",
    "            \"label\": label,\n",
    "            \"pos\": pos\n",
    "        })\n",
    "        return self\n",
    "\n",
    "    def add_screw_counter_sunk(self, block: cq.Workplane, mask: cq.Workplane):\n",
    "        self._screw_counter_sunks.append((block, mask))\n",
    "\n",
    "    def assemble(self):\n",
    "        wall = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .workplane()\n",
    "                .box(self.size.width - self.lid_size_error_margin, self.size.length - self.lid_size_error_margin, self.size.wall_thickness,\n",
    "                     centered=(True, True, False))\n",
    "        )\n",
    "        self.panel = cq.Assembly(None, name=\"Panel TOP\")\n",
    "        for part_to_add in self._parts_to_add:\n",
    "            part_obj = part_to_add[\"part\"]\n",
    "            self._add_part_to_debug_assemblies(part_to_add)\n",
    "            wall = wall.cut(\n",
    "                part_obj.mask.translate([*part_to_add[\"pos\"], 0])\n",
    "            )\n",
    "            if part_obj.assembly_parts != None:\n",
    "                self.panel = self.panel.add(\n",
    "                    self._translate_assembly_objects_and_rotate_to_face(part_obj.assembly_parts, [*part_to_add[\"pos\"], 0]))\n",
    "                    #self._rotate_assembly_to_face(part_obj.part_assembly.translate([*part_to_add[\"pos\"], 0])))\n",
    "            else:\n",
    "                self.panel = self.panel.add(\n",
    "                    self._rotate_to_face(\n",
    "                        part_obj.part.translate([*part_to_add[\"pos\"], 0])),\n",
    "                    name=part_to_add[\"label\"],\n",
    "                    color=cq.Color(*self._part_color, 1.0)\n",
    "                )\n",
    "            if part_obj.size.thickness > self.size.total_thickness:\n",
    "                self.size.total_thickness = part_obj.size.thickness\n",
    "        for screw_cs in self._screw_counter_sunks:\n",
    "            wall = wall.cut(screw_cs[1]).add(screw_cs[0])\n",
    "        self.panel = self.panel.add(self._rotate_to_face(wall), name=\"Wall\", color=cq.Color(*self._color, self._alpha))\n",
    "        self.debug_assemblies[\"combined\"] = self._build_combined_debug_assembly()\n",
    "        return self\n",
    "\n",
    "    def _rotate_to_face(self, wp):\n",
    "        if self.face == Face.TOP:\n",
    "            wp = wp.mirror(\"XY\")\n",
    "        elif self.face == Face.BOTTOM:\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        elif self.face == Face.BACK:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.mirror(\"YZ\")\n",
    "        elif self.face == Face.FRONT:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        elif self.face == Face.LEFT:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.rotate((0, 0, 0), (0, 0, 1), 90)\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        elif self.face == Face.RIGHT:\n",
    "            wp = wp.rotate((0, 0, 0), (1, 0, 0), 90)\n",
    "            wp = wp.rotate((0, 0, 0), (0, 0, 1), -90)\n",
    "            wp = wp.mirror(\"XZ\")\n",
    "        return wp\n",
    "\n",
    "    def _translate_assembly_objects_and_rotate_to_face(self, assembly_parts, translation):\n",
    "        assembly = cq.Assembly()\n",
    "        for assembly_part in assembly_parts:\n",
    "            part, loc, name, color = assembly_part.as_assembly_add_parameters()\n",
    "            part = part.translate(translation)\n",
    "            part = self._rotate_to_face(part)\n",
    "            assembly.add(part, name=name, color=color)\n",
    "        return assembly\n",
    "\n",
    "    def _add_part_to_debug_assemblies(self, part_to_add):\n",
    "        part = part_to_add[\"part\"]\n",
    "        part_pos = part_to_add[\"pos\"]\n",
    "        part_label: str = part_to_add[\"label\"]\n",
    "        if part.debug_objects.hole != None:\n",
    "            if self.debug_assemblies[\"hole\"] == None:\n",
    "                self.debug_assemblies[\"hole\"] = cq.Assembly()\n",
    "            hole = self._rotate_to_face(part.debug_objects.hole.translate([*part_pos, 0]))\n",
    "            self.debug_assemblies[\"hole\"] = self.debug_assemblies[\"hole\"].add(hole, name=part_label, color=cq.Color(1, 0, 0))\n",
    "        if part.debug_objects.footprint.inside != None:\n",
    "            if self.debug_assemblies[\"footprint_in\"] == None:\n",
    "                self.debug_assemblies[\"footprint_in\"] = cq.Assembly()\n",
    "            footprint_in = self._rotate_to_face(part.debug_objects.footprint.inside.translate([*part_pos, 0]))\n",
    "            self.debug_assemblies[\"footprint_in\"] = self.debug_assemblies[\"footprint_in\"].add(footprint_in, name=part_label, color=cq.Color(1, 0, 1))\n",
    "        if part.debug_objects.footprint.outside != None:\n",
    "            if self.debug_assemblies[\"footprint_out\"] == None:\n",
    "                self.debug_assemblies[\"footprint_out\"] = cq.Assembly()\n",
    "            footprint_out = self._rotate_to_face(part.debug_objects.footprint.outside.translate([*part_pos, 0]))\n",
    "            self.debug_assemblies[\"footprint_out\"] = self.debug_assemblies[\"footprint_out\"].add(footprint_out, name=part_label, color=cq.Color(0, 1, 1))\n",
    "        other_debug_assembly = None\n",
    "        for key in part.debug_objects.others.keys():\n",
    "            if other_debug_assembly == None:\n",
    "                other_debug_assembly = cq.Assembly(None)\n",
    "                self.debug_assemblies[\"other\"] = cq.Assembly()\n",
    "            debug_part = self._rotate_to_face(part.debug_objects.others[key].translate([*part_pos, 0]))\n",
    "            other_debug_assembly = other_debug_assembly.add(debug_part, name=key)\n",
    "        if other_debug_assembly != None:\n",
    "            if self.debug_assemblies[\"other\"] == None:\n",
    "                self.debug_assemblies[\"other\"] = cq.Assembly()\n",
    "            self.debug_assemblies[\"other\"] = self.debug_assemblies[\"other\"].add(other_debug_assembly, name=part_label, color=cq.Color(1, 1, 0))\n",
    "\n",
    "    def _build_combined_debug_assembly(self):\n",
    "        combined = self.debug_assemblies[\"combined\"]\n",
    "        combined = combined.add(self.mask, name=\"Mask\", color=cq.Color(0, 1, 0, 0.5))\n",
    "        if self.debug_assemblies[\"hole\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"hole\"], name=\"Holes\")\n",
    "        if self.debug_assemblies[\"footprint_in\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"footprint_in\"], name=\"Footprint in\")\n",
    "        if self.debug_assemblies[\"footprint_out\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"footprint_out\"], name=\"Footprint out\")\n",
    "        if self.debug_assemblies[\"other\"] != None:\n",
    "            combined = combined.add(self.debug_assemblies[\"other\"], name=\"Other\")\n",
    "        return combined\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9c235a8e-c687-4873-acea-7e6c4c648556",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100% ⋮————————————————————————————————————————————————————————————⋮ (4/4)  0.30s\n"
     ]
    }
   ],
   "source": [
    "from cq_enclosure_builder.parts.common.screw_block import ScrewBlock\n",
    "from cq_enclosure_builder.parts.common.screws_providers import DefaultFlatHeadScrewProvider, DefaultHeatSetScrewProvider\n",
    "\n",
    "screw = ScrewBlock(screw_provider=DefaultFlatHeadScrewProvider,\n",
    "                   counter_sunk_screw_provider=DefaultFlatHeadScrewProvider\n",
    "        ).m3(6, is_counter_sunk=True, with_counter_sunk_block=True)\n",
    "\n",
    "a = (\n",
    "    cq.Assembly(None, name=\"Screw block\")\n",
    "        .add(screw[\"block\"], name=\"Block\", color=cq.Color(1, 0, 0))\n",
    "        .add(screw[\"mask\"], name=\"Block Mask\", color=cq.Color(0, 1, 0))\n",
    "        .add(screw[\"counter_sunk_block\"], name=\"CS Block\", color=cq.Color(0, 1, 1))\n",
    "        .add(screw[\"counter_sunk_mask\"], name=\"CS Block Mask\", color=cq.Color(0, 1, 0))\n",
    ")\n",
    "show(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1f5e3a2c-0f4f-4cb6-b035-17cd448bbe18",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "from typing import List\n",
    "\n",
    "from cq_enclosure_builder.parts.common.screw_block import ScrewBlock, TaperOptions\n",
    "from cq_enclosure_builder.parts.common.screws_providers import DefaultFlatHeadScrewProvider, DefaultHeatSetScrewProvider\n",
    "\n",
    "def explode(pos_array, walls_explosion_factor=2.0):\n",
    "    return [x * walls_explosion_factor for x in pos_array]\n",
    "\n",
    "class EnclosureSize:\n",
    "    def __init__(self, inner_width, inner_length, inner_thickness, wall_thickness):\n",
    "        self.inner_width = inner_width\n",
    "        self.inner_length = inner_length\n",
    "        self.inner_thickness = inner_thickness\n",
    "        self.wall_thickness = wall_thickness\n",
    "\n",
    "class Enclosure:\n",
    "    def __init__(\n",
    "        self,\n",
    "        size: EnclosureSize,\n",
    "        lid_on_faces: List[Face] = [Face.BOTTOM],\n",
    "        lid_panel_size_error_margin = 0.8,  # meaning the lid is `margin` smaller than the hole on both width and length\n",
    "        lid_screws_thickness_error_margin = 0.4,\n",
    "        add_corner_lid_screws = True,\n",
    "        lid_screws_heat_set = True,\n",
    "        no_fillet_top = False,\n",
    "        no_fillet_bottom = False,\n",
    "        \n",
    "    ):\n",
    "        super().__init__()\n",
    "\n",
    "        inner_width = size.inner_width\n",
    "        inner_length = size.inner_length\n",
    "        inner_thickness = size.inner_thickness\n",
    "        wall_thickness = size.wall_thickness\n",
    "        self.size = size\n",
    "        self.no_fillet_top = no_fillet_top\n",
    "        self.no_fillet_bottom = no_fillet_bottom\n",
    "\n",
    "        if lid_on_faces != [Face.BOTTOM]:\n",
    "            # TODO: add support (upddate the correct face in panels_specs)\n",
    "            # TODO nice-to-have: also add support for multiple lids (faces)\n",
    "            raise ValueError(\"lid_on_faces: only value supported for now is [BOTTOM], got \" + str(lid_on_faces))\n",
    "\n",
    "        self.frame = (\n",
    "            cq.Workplane(\"front\")\n",
    "                .box(inner_width - 4, inner_length - 4, inner_thickness - 4, centered=(True, True, False))\n",
    "                #.faces(\"+Z\")\n",
    "                .shell(wall_thickness)\n",
    "                #.translate([2, 2, 2])\n",
    "        )\n",
    "        self.panels_specs = [\n",
    "            (Face.TOP,    (inner_width-4,  inner_length-4,    wall_thickness),  [0, 0, inner_thickness - wall_thickness],   0.9 ),\n",
    "            (Face.BOTTOM, (inner_width-4,  inner_length-4,    wall_thickness),  [0, 0, -wall_thickness],    0.9 ),\n",
    "            (Face.FRONT,  (inner_width-4,  inner_thickness-4, wall_thickness),  [0, -(inner_length/2), inner_thickness/2 - wall_thickness], 0.9 ),\n",
    "            (Face.BACK,   (inner_width-4,  inner_thickness-4, wall_thickness),  [0, inner_length/2, inner_thickness/2 - wall_thickness],  0.9 ),\n",
    "            (Face.LEFT,   (inner_length-4, inner_thickness-4, wall_thickness),  [-(inner_width/2), 0, inner_thickness/2 - wall_thickness], 0.9 ),\n",
    "            (Face.RIGHT,  (inner_length-4, inner_thickness-4, wall_thickness),  [inner_width/2, 0, inner_thickness/2 - wall_thickness],  0.9 ),\n",
    "        ]\n",
    "\n",
    "        self.panels = {}\n",
    "        self.screws_specs = []\n",
    "        self.screws = []\n",
    "\n",
    "        for info in self.panels_specs:\n",
    "            lid_size_error_margin = 0 if info[0] not in lid_on_faces else lid_panel_size_error_margin\n",
    "            self.panels[info[0]] = Panel(info[0], *info[1], alpha=info[3], lid_size_error_margin=lid_size_error_margin)\n",
    "\n",
    "        if add_corner_lid_screws:\n",
    "            self.add_corner_lid_screws(lid_screws_thickness_error_margin, heat_set=lid_screws_heat_set)\n",
    "\n",
    "    def add_part_to_face(self, face: Face, part_label: str, part: Part, rel_pos=None, abs_pos=None):\n",
    "        self.panels[face].add(part_label, part, rel_pos, abs_pos)\n",
    "        return self\n",
    "\n",
    "    def add_screw(\n",
    "        self,\n",
    "        screw_size_category: str = \"m3\",\n",
    "        block_thickness: float = 8,\n",
    "        rel_pos = None,\n",
    "        abs_pos = None,\n",
    "        pos_error_margin = 0,\n",
    "        taper: TaperOptions = TaperOptions.NO_TAPER,\n",
    "        taper_rotation: float = 0.0,\n",
    "        screw_provider = DefaultFlatHeadScrewProvider,\n",
    "        counter_sunk_screw_provider = DefaultFlatHeadScrewProvider,\n",
    "        with_counter_sunk_block = True\n",
    "    ):\n",
    "        # TODO support lid != Face.BOTTOM + refactor\n",
    "\n",
    "        pos = None\n",
    "        if rel_pos == None and abs_pos == None:\n",
    "            raise ValueError(\"Either rel_pos or abs_pos must be set.\")\n",
    "        elif rel_pos == None:\n",
    "            pos = (\n",
    "                abs_pos[0] - self.size.inner_width/2,\n",
    "                abs_pos[1] - self.size.inner_length/2\n",
    "            )\n",
    "        elif abs_pos==None:\n",
    "            pos = rel_pos\n",
    "\n",
    "        screw = ScrewBlock(screw_provider, counter_sunk_screw_provider).build(\n",
    "            screw_size_category,\n",
    "            block_thickness=block_thickness,\n",
    "            enclosure_wall_thickness=self.size.wall_thickness,\n",
    "            taper=taper,\n",
    "            taper_rotation=taper_rotation,\n",
    "            with_counter_sunk_block=with_counter_sunk_block\n",
    "        )\n",
    "        \n",
    "        screw[\"block\"] = screw[\"block\"].translate([*pos, pos_error_margin])\n",
    "        screw[\"mask\"] = screw[\"mask\"].translate([*pos, pos_error_margin])\n",
    "        if with_counter_sunk_block:\n",
    "            screw[\"counter_sunk_block\"] = screw[\"counter_sunk_block\"].translate([*pos, pos_error_margin])\n",
    "            screw[\"counter_sunk_mask\"] = screw[\"counter_sunk_mask\"].translate([*pos, pos_error_margin])\n",
    "        self.screws.append(screw)\n",
    "        return screw\n",
    "\n",
    "    def add_corner_lid_screws(\n",
    "        self,\n",
    "        lid_screws_thickness_error_margin,\n",
    "        screw_size_category: str = \"m2\",\n",
    "        heat_set: bool = False\n",
    "    ):\n",
    "        # TODO support lid != Face.BOTTOM + refactor\n",
    "\n",
    "        lid_screws_thickness = 8\n",
    "\n",
    "        screw_provider = DefaultHeatSetScrewProvider if heat_set else DefaultFlatHeadScrewProvider\n",
    "\n",
    "        screw_size = ScrewBlock(screw_provider).build(screw_size_category, lid_screws_thickness, self.size.wall_thickness)[\"size\"]  # refactor to avoid this\n",
    "        pw = self.size.inner_width\n",
    "        pl = self.size.inner_length\n",
    "        sw = screw_size[0]\n",
    "        sl = screw_size[1]\n",
    "        wt = self.size.wall_thickness\n",
    "        corners = [\n",
    "            ( (0+sw/2+wt,  0+sl/2+wt),    0 ),\n",
    "            ( (0+sw/2+wt,  pl-sl/2-wt),  90 ),\n",
    "            ( (pw-sw/2-wt, pl-sl/2-wt), 180 ),\n",
    "            ( (pw-sw/2-wt, 0+sl/2+wt),  270 )\n",
    "        ]\n",
    "        for c in corners:\n",
    "            screw_pos = c[0]\n",
    "            screw_rotation = c[1]\n",
    "            screw = self.add_screw(\n",
    "                screw_size_category=screw_size_category,\n",
    "                block_thickness=lid_screws_thickness,\n",
    "                abs_pos=screw_pos,\n",
    "                pos_error_margin=lid_screws_thickness_error_margin,\n",
    "                taper=TaperOptions.Z_TAPER_ANGLE,\n",
    "                taper_rotation=screw_rotation,\n",
    "                with_counter_sunk_block=True,\n",
    "                screw_provider=screw_provider\n",
    "            )\n",
    "            translate_z = screw[\"size\"][2] + lid_screws_thickness_error_margin + self.size.wall_thickness\n",
    "            cs_block = screw[\"counter_sunk_block\"].rotate((0, 0, 0), (1, 0, 0), 180).translate([0, 0, translate_z])\n",
    "            cs_mask = screw[\"counter_sunk_mask\"].rotate((0, 0, 0), (1, 0, 0), 180).translate([0, 0, translate_z])\n",
    "            self.panels[Face.BOTTOM].add_screw_counter_sunk(cs_block, cs_mask)\n",
    "\n",
    "    def assemble(self, walls_explosion_factor=1.0, lid_panel_shift=0.0):\n",
    "        for panel in self.panels.values():\n",
    "            panel.assemble()\n",
    "\n",
    "        panels_assembly, panels_masks_assembly = self._build_panels_assembly(walls_explosion_factor, lid_panel_shift)\n",
    "        frame_assembly = self._build_frame_assembly(panels_masks_assembly)\n",
    "        lid_screws_assembly = self._build_lid_screws_assembly()\n",
    "\n",
    "        footprints_assembly = self._build_debug_assembly([(\"footprint_in\", \"I\"), (\"footprint_out\", \"O\")], walls_explosion_factor, lid_panel_shift)\n",
    "        holes_assembly = self._build_debug_assembly([(\"hole\", \"\")], walls_explosion_factor, lid_panel_shift)\n",
    "        other_debug_assembly = self._build_debug_assembly([(\"other\", \"\")], walls_explosion_factor, lid_panel_shift)\n",
    "\n",
    "        self.debug = (\n",
    "            cq.Assembly(None, name=\"Box\")\n",
    "                .add(footprints_assembly, name=\"Footprints\")\n",
    "                .add(holes_assembly, name=\"Holes\")\n",
    "                .add(other_debug_assembly, name=\"Others\")\n",
    "                .add(panels_masks_assembly, name=\"Panels masks\")\n",
    "        )\n",
    "        self.assembly = (\n",
    "            cq.Assembly(None, name=\"Box\")\n",
    "                .add(panels_assembly, name=\"Panels\")\n",
    "                .add(frame_assembly, name=\"Frame\")\n",
    "                .add(lid_screws_assembly, name=\"Lid screws\", color=cq.Color(0.6, 0.45, 0.8))\n",
    "                .add(self.debug, name=\"Debug\")\n",
    "        )\n",
    "        self.printable_assembly = (\n",
    "            cq.Assembly(None, name=\"Box\")\n",
    "                .add(panels_assembly, name=\"Panels\")\n",
    "                .add(frame_assembly, name=\"Frame\")\n",
    "                .add(lid_screws_assembly, name=\"Lid screws\", color=cq.Color(0.6, 0.45, 0.8))\n",
    "        )\n",
    "        return self\n",
    "\n",
    "    def _get_debug(self, panel: Panel, assembly_name=\"combined\"):\n",
    "        if assembly_name in panel.debug_assemblies:\n",
    "            return panel.debug_assemblies[assembly_name]\n",
    "        return None\n",
    "\n",
    "    def _build_panels_assembly(self, walls_explosion_factor, lid_panel_shift):\n",
    "        a = cq.Assembly(None)\n",
    "        masks_a = cq.Assembly(None)\n",
    "        for face, size, position, alpha in self.panels_specs:\n",
    "            panel: Panel = self.panels[face]\n",
    "            translated_mask = panel.mask.translate(position)\n",
    "            masks_a.add(translated_mask, name=(face.label + \" mask\"), color=cq.Color(0, 1, 0))\n",
    "            if face == Face.BOTTOM:\n",
    "                position = (position[0], position[1], position[2] - lid_panel_shift)\n",
    "            translated_panel = panel.panel.translate(explode(position, walls_explosion_factor))\n",
    "            a.add(translated_panel, name=face.label)\n",
    "        return (a, masks_a)\n",
    "\n",
    "    def _build_frame_assembly(self, panels_masks_assembly) -> cq.Workplane:\n",
    "        \"\"\"\n",
    "        Get the frame of the enclosure (the masks of the panels will be .cut during the assembly).\n",
    "        In this implemenmtation, it's only possible to remove the fillet\n",
    "        on the top and bottom of the enclosure (TODO: better implementation needed when lid_on_faces != [Face.BOTTOM] allowed),\n",
    "        but you can to override the method if you need something more custom (and feel free to contribute ;) )\n",
    "        \"\"\"\n",
    "        # TODO: when implementing the lid on other faces than BOTTOM, will have to remake that code better\n",
    "\n",
    "        wall_thickness = self.size.wall_thickness\n",
    "\n",
    "        shell_faces_filter = []\n",
    "        shell_size = [\n",
    "            self.size.inner_width - wall_thickness*2,\n",
    "            self.size.inner_length - wall_thickness*2,\n",
    "            self.size.inner_thickness - wall_thickness*2\n",
    "        ]\n",
    "        shell_translate_z = 0\n",
    "\n",
    "        if self.no_fillet_top:\n",
    "            shell_faces_filter.append(\"+Z\")\n",
    "            shell_size[2] = shell_size[2] + wall_thickness\n",
    "            shell_translate_z = shell_translate_z# + wall_thickness\n",
    "        if self.no_fillet_bottom:\n",
    "            shell_faces_filter.append(\"-Z\")\n",
    "            shell_size[2] = shell_size[2] + wall_thickness\n",
    "            shell_translate_z = shell_translate_z - wall_thickness\n",
    "\n",
    "        no_faces_filter = \"+Z and -Z\"  # as two faces cannot be true at once--cheeky way to avoid `.faces(\"\")`\n",
    "        shell_faces = no_faces_filter if len(shell_faces_filter) == 0 else \" or \".join(shell_faces_filter)\n",
    "\n",
    "        shell = (\n",
    "            cq.Workplane()\n",
    "                .box(*shell_size, centered=(True, True, False))\n",
    "                .faces(shell_faces)\n",
    "                .shell(wall_thickness)\n",
    "                .translate([0, 0, shell_translate_z])\n",
    "        )\n",
    "\n",
    "        return shell.cut(panels_masks_assembly.toCompound())\n",
    "\n",
    "    def _build_lid_screws_assembly(self):\n",
    "        a = cq.Assembly(None)\n",
    "        for idx, s in enumerate(self.screws):\n",
    "            a.add(s[\"block\"], name=f\"Screw #{idx}\", color=cq.Color(0.6, 0.45, 0.8))\n",
    "        return a\n",
    "\n",
    "    def _cut_panels_masks_from_frame(self, frame: cq.Workplane) -> cq.Workplane:\n",
    "        for face, size, position, alpha in self.panels_specs:\n",
    "            panel: Panel = self.panels[face]\n",
    "            translated_mask = panel.mask.translate(position)\n",
    "            frame = frame.cut(translated_mask)\n",
    "        return frame\n",
    "\n",
    "    def _build_debug_assembly(self, assemblies_specs, walls_explosion_factor, lid_panel_shift):\n",
    "        a = cq.Assembly(None)\n",
    "        for face, size, position, alpha in self.panels_specs:\n",
    "            if face == Face.BOTTOM:\n",
    "                position = (position[0], position[1], position[2] - lid_panel_shift)\n",
    "            panel: Panel = self.panels[face]\n",
    "            for assembly_type, assembly_name_suffix in assemblies_specs:\n",
    "                debug_assembly = self._get_debug(panel, assembly_type)\n",
    "                if debug_assembly != None:\n",
    "                    translated_debug = debug_assembly.translate(explode(position, walls_explosion_factor))\n",
    "                    a.add(translated_debug, name=(f\"{face.label} {assembly_name_suffix}\"))\n",
    "        return a"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "9ea3d1f9-f421-48eb-9b3a-630066e0daf3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "VALIDATING CLASS: RectAirVentPart\n",
      "VALIDATING CLASS: RectAirVentPart\n",
      "VALIDATING CLASS: RectAirVentPart\n",
      "VALIDATING CLASS: RectAirVentPart\n",
      "LEFT: adding part 'Vent L'\n",
      "BACK: adding part 'Vent B1'\n",
      "BACK: adding part 'Vent B2'\n",
      "VALIDATING CLASS: ButtonSpstPbs24b4Part\n",
      "TOP: adding part 'SPST 1'\n",
      "VALIDATING CLASS: PyramidSupportPart\n",
      "BOTTOM: adding part 'Support SPST'\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (48/48)  2.13s\n"
     ]
    }
   ],
   "source": [
    "from cq_enclosure_builder import PartFactory as pf\n",
    "from cq_enclosure_builder.parts.air_vent.fan_size import FanSize\n",
    "\n",
    "pf.set_default_types({\n",
    "    \"air_vent\": 'basic rectangular',\n",
    "})\n",
    "\n",
    "vent_l = pf.build_air_vent(enclosure_wall_thickness=2)\n",
    "\n",
    "#pf.build_air_vent(enclosure_wall_thickness=2, width=30, length=25, thickness=5, with_fan_screws=FanSize._30_MM, hole_angle=25, hole_width=1.6, distance_between_holes=3)\n",
    "\n",
    "vent_r = pf.build_air_vent(enclosure_wall_thickness=2, width=30, length=25, thickness=5, hole_angle=25, hole_width=1.6, distance_between_holes=3)\n",
    "vent_b1 = pf.build_air_vent(enclosure_wall_thickness=2, width=30, length=26, thickness=8, with_fan_screws=FanSize._25_MM, taper_margin=4, hole_angle=15, hole_width=1.2, distance_between_holes=2.1)\n",
    "vent_b2 = pf.build_air_vent(enclosure_wall_thickness=2, width=30, length=26, thickness=3, hole_angle=35, hole_width=0.6, distance_between_holes=1.35)\n",
    "\n",
    "enclosure = Enclosure(EnclosureSize(120, 80, 42, 2), lid_screws_heat_set=True)\n",
    "enclosure.add_part_to_face(Face.LEFT, \"Vent L\", vent_l, rel_pos=(0, 0))\n",
    "# enclosure.add_part_to_face(Face.RIGHT, \"Vent R\", vent_r, rel_pos=(0, 0))\n",
    "enclosure.add_part_to_face(Face.BACK, \"Vent B1\", vent_b1, rel_pos=(-20, 0))\n",
    "enclosure.add_part_to_face(Face.BACK, \"Vent B2\", vent_b2, rel_pos=(20, 0))\n",
    "enclosure.add_part_to_face(Face.TOP, \"SPST 1\", pf.build_button(), abs_pos=(20, 30))\n",
    "enclosure.add_part_to_face(Face.BOTTOM, \"Support SPST\", pf.build_support(part_type=\"pyramid\", support_height=17), abs_pos=(20, 80-30-2*2))\n",
    "enclosure.assemble(lid_panel_shift=50)\n",
    "\n",
    "show(enclosure.assembly, hide_contains=[\"masks\", \"FRONT\", \"BOTTOM\", \"Debug\"])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "48d1557c-2df6-4c45-9f27-535a9ea1e670",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3e862dc-d0ac-4e29-a453-e5742a823efd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "3747baa6-487d-4b47-8f85-e64cbf38357f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Building CS cat m3 - ref M3-0.5\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (2/2)  0.45s\n"
     ]
    }
   ],
   "source": [
    "screw = ScrewBlock().m3(8, 2, with_counter_sunk_block=True)\n",
    "a = cq.Assembly().add(screw[\"block\"]).add(screw[\"counter_sunk_block\"])\n",
    "a"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "431c05f5-5f1e-450a-b853-29ec540bef7f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "281633aa-b6d1-4453-a96e-d7e0a737f078",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ENCLOSURE_INNER_WIDTH =     220\n",
    "# ENCLOSURE_INNER_LENGTH =    150\n",
    "# ENCLOSURE_INNER_THICKNESS = 38\n",
    "# ENCLOSURE_WALLS_THICKNESS = 2\n",
    "\n",
    "# enclosure_size = EnclosureSize(ENCLOSURE_INNER_WIDTH, ENCLOSURE_INNER_LENGTH, ENCLOSURE_INNER_THICKNESS, ENCLOSURE_WALLS_THICKNESS)\n",
    "# enclosure = Enclosure(size=enclosure_size, no_fillet_bottom=True, no_fillet_top=True)\n",
    "# enclosure.add_part_to_face(Face.TOP, \"Screen\", pf.build_screen(), rel_pos=(0, -4))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"SPST 1\", pf.build_button(), abs_pos=(20, 30))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"SPST 2\", pf.build_button(), abs_pos=(20, 100))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"SPST 3\", pf.build_button(), abs_pos=(200, 30))\n",
    "# enclosure.add_part_to_face(Face.TOP, \"Encoder\", pf.build_encoder(), abs_pos=(200, 100))\n",
    "# for i in range(0, 4):\n",
    "#     enclosure.add_part_to_face(Face.BACK, f\"Js{i}\", pf.build_jack(part_type='3.5mm XXX'), abs_pos=(8, 4.5 + i*9))\n",
    "# for i in range(0, 7):\n",
    "#     enclosure.add_part_to_face(Face.BACK, f\"Jb{i}\", pf.build_jack(), abs_pos=(24 + i*18, 10))\n",
    "#     enclosure.add_part_to_face(Face.BACK, f\"Jt{i}\", pf.build_jack(), abs_pos=(24 + i*18, 18+9))\n",
    "# enclosure.add_part_to_face(Face.LEFT, \"USB\", pf.build_usb_a(), rel_pos=(0, 0))\n",
    "# enclosure.add_part_to_face(Face.LEFT, \"USB V\", pf.build_usb_a(orientation_vertical=True), rel_pos=(40, 0))\n",
    "# enclosure.add_part_to_face(Face.RIGHT, \"USB C\", pf.build_usb_c(), rel_pos=(0, 0))\n",
    "# enclosure.add_part_to_face(Face.RIGHT, \"USB C\", pf.build_usb_c(), rel_pos=(0, 0))\n",
    "\n",
    "# enclosure.assemble(walls_explosion_factor=1.0, lid_panel_shift=100)\n",
    "\n",
    "# show(enclosure.printable_assembly, hide_contains=[\"gfg\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "fe4bc8b3-c776-4548-becd-50c381a23ffb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "VALIDATING CLASS: RectAirVentPart\n",
      "100% ⋮————————————————————————————————————————————————————————————⋮ (6/6)  0.65s\n"
     ]
    }
   ],
   "source": [
    "pf.set_default_types({\n",
    "    \"air_vent\": 'basic rectangular',\n",
    "})\n",
    "\n",
    "av = pf.build_air_vent()\n",
    "\n",
    "show_part(av)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58f88881-f8a8-4d74-a450-29aef66bc850",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4167e991-5ac9-48a0-b549-b5c4fb3ede54",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "18874b4f-30cb-4fa4-8663-055f4010dfe3",
   "metadata": {},
   "source": [
    "# TODO"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "800a2df9-450d-42c4-a027-24e944d063f3",
   "metadata": {},
   "source": [
    "- [x] Add counter-sunk hole in lid\n",
    "- [x] Add footprint for vent\n",
    "- [ ] Add tapered block on the lid; (??)\n",
    "- [ ] Add support 'skirt' on the top part\n",
    "- [ ] Enclosure#export_printables;\n",
    "- [ ] Layout builder: 'left of', 'right of' (problem with the screen not being centered.)\n",
    "    - First: check TODO in screen\n",
    "- Add parts:\n",
    "    - [ ] MIDI\n",
    "    - [ ] DPDT\n",
    "    - [ ] Switch\n",
    "    - [ ] Tiny button\n",
    "    - [ ] Big button"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a93a9eb0-5ac9-4e05-9cd0-13eb301c5bbe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
